FROM amd64/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN apt-get update && apt-get install -y bash net-tools && apt-get clean

RUN useradd -ms /bin/bash cl

RUN mkdir /etc/cl

RUN mkdir /var/lib/cl

RUN chown cl:cl /etc/cl /var/lib/cl

WORKDIR /home/cl

COPY --chown=cl:cl linux64/* /home/cl/

COPY --chown=cl:cl run.sh /home/cl/

USER cl

CMD ["/home/cl/run.sh"]
